openshift_cluster_content:
- object: projects
  content:
  - name: "create environments"
    file: "{{role_path}}/../../applier/deploy-tasks-app/projects/projects.yml"
    action: create
- object: limitrange
  content:
  - name: "create limitrange"
    file: "{{role_path}}/../../applier/deploy-tasks-app/limitrange/limitrange.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/deployment-dev"
    action: create
    namespace: "{{tasks_dev_namespace}}"
  - name: "create limitrange stage"
    file: "{{role_path}}/../../applier/deploy-tasks-app/limitrange/limitrange.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/deployment-stage"
    action: create
    namespace: "{{tasks_stage_namespace}}"
  - name: "create limitrange prod"
    file: "{{role_path}}/../../applier/deploy-tasks-app/limitrange/limitrange.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/deployment-prod"
    action: create
    namespace: "{{tasks_prod_namespace}}"

- object: hpa
  content:
  - name: "create hpa"
    file: "{{role_path}}/../../applier/deploy-tasks-app/hpa/hpa.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/deployment-dev"
    action: create
    namespace: "{{tasks_dev_namespace}}"
  - name: "create hpa stage"
    file: "{{role_path}}/../../applier/deploy-tasks-app/hpa/hpa.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/deployment-stage"
    action: create
    namespace: "{{tasks_stage_namespace}}"
  - name: "create hpa prod "
    file: "{{role_path}}/../../applier/deploy-tasks-app/hpa/hpa.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/deployment-prod"
    action: create
    namespace: "{{tasks_prod_namespace}}"

- object: deployments
  content:
  - name: "deploy dev environment"
    template: "{{role_path}}/../../applier/deploy-tasks-app/templates/deployment.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/deployment-dev"
  - name: "deply stage environment"
    template: "{{role_path}}/../../applier/deploy-tasks-app/templates/deployment.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/deployment-stage"
  - name: "deply prod environment"
    template: "{{role_path}}/../../applier/deploy-tasks-app/templates/deployment.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/deployment-prod"
- object: builds
  content:
  - name: "deploy build pipeline to dev"
    template: "{{role_path}}/../../applier/deploy-tasks-app/templates/build.yml"
    params: "{{role_path}}/../../applier/deploy-tasks-app/params/build-dev"
