---
- name: All GUID env variable
  shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc
  tags: set-guid 

- name: Verify Docker installation
  yum: 
    name: docker
    state: present
  tags: verify-docker
 
- name: Configuration of Docker
  shell: systemctl restart docker
  tags: verify-docker 

- name: Verify NFS installed on nfs node
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nfs-utils
    - rpcbind
  tags: verify-nfs
