---
- name: Set GUID in host file
  hosts: localhost
  roles:
    - inventory

- name: Prepare Environment Play
  hosts: all
  roles:
    - prep-env

- name: install pre-req
  import_playbook: "/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml"

- name: install ansible
  import_playbook: "/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml"

- name: Post Install
  hosts: all,localhost
  roles:
    - post-install

- name: Smoke Test
  hosts: localhost
  roles:
    - smoke-test

- name: Deploy Jenkins
  hosts: localhost
  roles:
    - cicd

- name: Prepare App Development
  hosts: localhost
  roles:
    - prepare-app-deployment

- name: Deploy OpenShift Tasks Project
  hosts: localhost
  roles:
    - openshift-applier
