---
- name: Set GUID in host file
  hosts: localhost
  roles:
    - inventory

- name: Prepare Environment Play
  hosts: all
  roles:
    - common-prep

- name: Verify Docker on nodes
  hosts: nodes
  roles:
    - docker-prep

- name: Verify NFS
  hosts: nfs
  roles:
    - nfs-prep

- name: install pre-req
  import_playbook: "/usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml"

- name: install ansible
  import_playbook: "/usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml"

- name: Post Install Verification
  hosts: localhost
  roles:
    - post-install-verify

- name: Post Install Configuration
  hosts: nfs
  roles:
    - post-install-configure
