---
- name: Prepare Environment Play
  hosts: all
  roles:
    - prep-env
  tags: set-guid

  hosts: nodes
  roles:
    - prep-env
  tags: verify-docker  

  hosts: nfs
  roles:
    - prep-env
  tags: verify-nfs
