---
- name: Prepare cluster for Multitenant project setup
  hosts: masters,localhost
  roles:
    - multitenant

- name: Smoke Test
  hosts: localhost
  roles:
    - smoke-test

- name: Deploy Jenkins
  hosts: localhost
  roles:
    - cicd

- name: Deploy OpenShift Tasks Project
  hosts: localhost
  roles:
    - deploy-app

