---
- name: create pv directories
  file:
    dest: "/srv/nfs/user-vols/pv{{ item }}"
    state: directory
    group: nfsnobody
    owner: nfsnobody
    mode: 0777
  with_sequence: start=1 end=50

- name: configure exports
  shell: echo /srv/nfs/user-vols/pv{{ item }} >> /etc/exports.d/openshift-uservols.exports
  with_sequence: start=1 end=50
 
