apiVersion: v1
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: limits
    namespace: ${NAMESPACE}
  spec:
    limits:
    - max:
        cpu: 100m
        memory: 750Mi
      min:
        cpu: 10m
        memory: 5Mi
      type: Pod
    - default:
        cpu: 50m
        memory: 100Mi
      defaultRequest:
        cpu: 50m
        memory: 100Mi
      max:
        cpu: 100m
        memory: 750Mi
      min:
        cpu: 10m
        memory: 5Mi
      type: Container
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

