apiVersion: v1
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: limits
  spec:
    limits:
    - max:
        cpu: 1000m
        memory: 1000Mi
      min:
        cpu: 250m
        memory: 500Mi
      type: Pod
    - default:
        cpu: 750m
        memory: 750Mi
      defaultRequest:
        cpu: 750m
        memory: 750Mi
      max:
        cpu: 1000m
        memory: 1000Mi
      min:
        cpu: 250m
        memory: 500Mi
      type: Container
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

