apiVersion: v1
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: limits
  spec:
    limits:
    - max:
        cpu: 500m
        memory: 1000Mi
      min:
        cpu: 100m
        memory: 100Mi
      type: Pod
    - default:
        cpu: 250m
        memory: 500Mi
      defaultRequest:
        cpu: 250m
        memory: 500Mi
      max:
        cpu: 500m
        memory: 1000Mi
      min:
        cpu: 100m
        memory: 100Mi
      type: Container
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

