apiVersion: v1
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: limits
  spec:
    limits:
    - max:
        cpu: 150m
        memory: 750Mi
      min:
        cpu: 50m
        memory: 10Mi
      type: Pod
    - default:
        cpu: 100m
        memory: 100Mi
      defaultRequest:
        cpu: 100m
        memory: 100Mi
      max:
        cpu: 150m
        memory: 750Mi
      min:
        cpu: 50m
        memory: 10Mi
      type: Container
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

