---
- name: add a host
  add_host:
    hostname: localhost
    groups:
      - seed-hosts
    ansible_connection: local
    ansible_host: localhost

- name: Include only files matching bastion.yaml (2.2)
  include_vars:
    dir: vars
    files_matching: seed-hosts.yml

- name: Apply condition to each task in role
  import_role:
    name: openshift-applier
  when: "inventory_hostname == 'localhost'"

