---
- name: add localhost to seed-hosts
  add_host:
    hostname: localhost
    groups:
      - seed-hosts
    ansible_connection: local
    ansible_host: localhost
  when: "inventory_hostname == 'localhost'"

- name: load inventory info for multitenant project template 
  include_vars:
    dir: vars
    files_matching: seed-hosts.yml
  when: "inventory_hostname == 'localhost'"

- name: Create project templates using applier
  import_role:
    name: openshift-applier
  when: "inventory_hostname == 'localhost'"

- name: copy podnodeselector yaml
  copy:
    src: "{{ role_path }}/files/podnodeSelectorConfig.yaml"
    dest: "/etc/origin/"
  when: "'masters' in group_names"

- name: backup master-config.yaml
  shell: 'cp /etc/origin/master/master-config.yaml /etc/origin/master/master-config.yaml_backup_multitenant'
  when: "'masters' in group_names"

- name: update master config file with admissionConfig
  shell: 'sed -i "/pluginConfig:/ a \    PodNodeSelector:\n      location: /etc/origin/podnodeSelectorConfig.yaml" /etc/origin/master/master-config.yaml'
  when: "'masters' in group_names"

- name: update master config file with default project template 
  lineinfile:
    dest: "/etc/origin/master/master-config.yaml"
    line: "  projectRequestTemplate: 'default/default-project-request'"
    regexp: "^(.*)projectRequestTemplate: ''(.*)$"
  when: "'masters' in group_names"

- name: stop master services
  shell: 'systemctl stop {{ item }}'
  with_items:
    - atomic-openshift-master-api
    - atomic-openshift-master-controllers
  when: "'masters' in group_names"

- name: start master services
  shell: 'systemctl start {{ item }}'
  with_items:
    - atomic-openshift-master-controllers
    - atomic-openshift-master-api
  when: "'masters' in group_names"

