---
- name: Verify NFS installed on nfs node
  yum: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - nfs-utils
    - rpcbind
  tags: verify-nfs

- name: check exportfs
  shell : exportfs
  tags: verify-nfs
