---

- name: "Copy 'file' to remote host"
  vars:
    file: "{{ entry.file }}"
  import_tasks: copy-inventory-file.yml
  when:
  - entry['file'] is defined
  - entry['file']|trim != ''

- name: "Copy 'template' to remote host"
  vars:
    file: "{{ entry.template }}"
  import_tasks: copy-inventory-file.yml
  when:
  - entry['template'] is defined
  - entry['template']|trim != ''

- name: "Copy 'params' to remote host"
  vars:
    file: "{{ entry.params }}"
  import_tasks: copy-inventory-file.yml
  when:
  - entry['params'] is defined
  - entry['params']|trim != ''
