---

- name: "Create a temporary directory to use" 
  tempfile:
    state: directory
  register: tmp_dir
  notify:
  - Clean up temporary inventory dir

- name: "Store away the temporary directory path"
  set_fact:
    tmp_inv_dir: "{{ tmp_dir.path }}/"

- name: "Copy local inventory files to target host(s)"
  include_tasks: copy-inventory-content.yml
  loop_control:
    loop_var: content_entry
  with_items:
  - "{{ openshift_cluster_content | filter_applier_items(filter_tags) | default([]) }}"
