---

- name: "Copy 'content' entries"
  include_tasks: copy-inventory-entry.yml
  loop_control:
    loop_var: entry
  with_items:
  - "{{ content_entry.content }}"
  when:
  - content_entry.content is defined
