---
- name: Smoke Test
  script: deploy-nodejs-mongodb-persistent.sh

- name: Test URL
  shell: echo http://$(sudo oc get route | awk 'NR>1 {print $2}')  
  register: url

- name: debug 
  debug:
    msg: "{{ url.stdout }}"

- name: "wait for pod to come up"
  uri:
    url: "{{ url.stdout }}"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 120
  delay: 2 

- name: Smoke Test Passed
  debug:
    msg: "***SMOKE TEST PASSED***"
  when: result.status == 200

