openshift_cluster_content:
# ALPHA CLIENT
- object: user
  content:
  - name: "create user amy"
    template: "{{role_path}}/../../applier/multitenant/user-group-templates/user-request-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/amy-env"

- object: user
  content:
  - name: "create user andrew"
    template: "{{role_path}}/../../applier/multitenant/user-group-templates/user-request-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/andrew-env"

- object: groups
  content:
  - name: "create groups"
    template: "{{role_path}}/../../applier/multitenant/user-group-templates/group-request-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/alpha-env"

- object: project 
  content:
  - name: "create project"
    template: "{{role_path}}/../../applier/multitenant/project-templates/multitenant-project-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/alpha-env"

- object: app
  content:
  - name: "deploy app"
    template: "{{role_path}}/../../applier/deploy-client-projects/templates/sample-app.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/alpha-env"

# BETA CLIENT

- object: user
  content:
  - name: "create user amy"
    template: "{{role_path}}/../../applier/multitenant/user-group-templates/user-request-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/brian-env"

- object: user
  content:
  - name: "create user andrew"
    template: "{{role_path}}/../../applier/multitenant/user-group-templates/user-request-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/betty-env"

- object: groups
  content:
  - name: "create groups"
    template: "{{role_path}}/../../applier/multitenant/user-group-templates/group-request-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/beta-env"

- object: project
  content:
  - name: "create project"
    template: "{{role_path}}/../../applier/multitenant/project-templates/multitenant-project-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/beta-env"

- object: app
  content:
  - name: "deploy app"
    template: "{{role_path}}/../../applier/deploy-client-projects/templates/sample-app.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/beta-env"

# CHARLIE CLIENT

- object: user
  content:
  - name: "create user amy"
    template: "{{role_path}}/../../applier/multitenant/user-group-templates/user-request-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/cain-env"

- object: user
  content:
  - name: "create user andrew"
    template: "{{role_path}}/../../applier/multitenant/user-group-templates/user-request-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/candy-env"

- object: groups
  content:
  - name: "create groups"
    template: "{{role_path}}/../../applier/multitenant/user-group-templates/group-request-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/charlie-env"

- object: project
  content:
  - name: "create project"
    template: "{{role_path}}/../../applier/multitenant/project-templates/multitenant-project-template.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/charlie-env"

- object: app
  content:
  - name: "deploy app"
    template: "{{role_path}}/../../applier/deploy-client-projects/templates/sample-app.yaml"
    params: "{{role_path}}/../../applier/deploy-client-projects/params/charlie-env"

